//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Utility.Globalize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hanodale.Utility.Globalize.Emails", typeof(Emails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 13pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActiveBusinessMasterBody {
            get {
                return ResourceManager.GetString("ActiveBusinessMasterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to UTW HRMS Management Solution.
        /// </summary>
        public static string ActiveBusinessMasterSubject {
            get {
                return ResourceManager.GetString("ActiveBusinessMasterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 11pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApprovalBody {
            get {
                return ResourceManager.GetString("ApprovalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 11pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 13pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChangedPasswordBody {
            get {
                return ResourceManager.GetString("ChangedPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartasset@malaysiaairports.com.my.
        /// </summary>
        public static string ChangedPasswordFrom {
            get {
                return ResourceManager.GetString("ChangedPasswordFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed!.
        /// </summary>
        public static string ChangedPasswordSubject {
            get {
                return ResourceManager.GetString("ChangedPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///				font-family: Arial;
        ///				font-size: 11pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 13pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fine-p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartasset@malaysiaairports.com.my.
        /// </summary>
        public static string ForgotPasswordFrom {
            get {
                return ResourceManager.GetString("ForgotPasswordFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Request.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 11pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InActiveBusinessMasterBody {
            get {
                return ResourceManager.GetString("InActiveBusinessMasterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Inactive.
        /// </summary>
        public static string InActiveBusinessMasterSubject {
            get {
                return ResourceManager.GetString("InActiveBusinessMasterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 11pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RFQAdjustmentBody {
            get {
                return ResourceManager.GetString("RFQAdjustmentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Updated ($CODE$).
        /// </summary>
        public static string RFQAdjustmentSubject {
            get {
                return ResourceManager.GetString("RFQAdjustmentSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 11pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RFQReleaseBody {
            get {
                return ResourceManager.GetString("RFQReleaseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Release ($CODE$).
        /// </summary>
        public static string RFQReleaseSubject {
            get {
                return ResourceManager.GetString("RFQReleaseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $SUBMENU$ &quot; $CODE$ ($APPROVALRESULT$).
        /// </summary>
        public static string SubmitForApprovalSubject {
            get {
                return ResourceManager.GetString("SubmitForApprovalSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 11pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubmittedForApprovalBody {
            get {
                return ResourceManager.GetString("SubmittedForApprovalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///       &lt;title&gt;&lt;/title&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;well&quot; style=&quot;padding: 40px 20px;&quot;&gt;
        ///        &lt;h1 class=&quot;grey lighter smaller&quot; style=&quot;padding-bottom: 10px;&quot;&gt;Terms &amp; Conditions
        ///        &lt;/h1&gt;
        ///        &lt;hr /&gt;
        ///        &lt;div class=&quot;slim-scroll&quot; data-height=&quot;300&quot;&gt;
        ///            &lt;div class=&quot;content&quot; style=&quot;margin-left: 14px;margin-right: 20px;&quot;&gt;
        ///		&lt;br/&gt;
        ///                &lt;!-- Terms &amp; Condition content --&gt;
        ///                &lt;h2&gt;Privacy Policy&lt;/h2&gt;
        ///		&lt;br/&gt;
        ///                &lt;h3&gt;1. Sharing of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TermConditions {
            get {
                return ResourceManager.GetString("TermConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 13pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 13pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserCreatedBody {
            get {
                return ResourceManager.GetString("UserCreatedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartasset@malaysiaairports.com.my.
        /// </summary>
        public static string UserCreatedFrom {
            get {
                return ResourceManager.GetString("UserCreatedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to UTW HRMS Management Solution.
        /// </summary>
        public static string UserCreatedSubject {
            get {
                return ResourceManager.GetString("UserCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 13pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 13pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserPasswordResetBody {
            get {
                return ResourceManager.GetString("UserPasswordResetBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string UserPasswordResetSubject {
            get {
                return ResourceManager.GetString("UserPasswordResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, td {
        ///				font-family: Arial;
        ///				font-size: 10pt;
        ///			}
        ///			
        ///			a, a:hover {
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.signature, .signature td {
        ///				font-family: Helvetica, Tahoma, Verdana, San-Serif;
        ///				font-size: 11pt;
        ///				font-weight: bold;
        ///				padding: 0;
        ///				border-spacing: 0;
        ///				margin: 0;
        ///			}
        ///			
        ///			.dk {
        ///				font-size: 21pt;
        ///				color: #919191;
        ///			}
        ///			
        ///			.company-name {
        ///				font-size: 9pt;
        ///				color: #3B99B6;
        ///			}
        ///			
        ///			.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WorkOrderBody {
            get {
                return ResourceManager.GetString("WorkOrderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order $CODE$ ($STATUS$).
        /// </summary>
        public static string WorkOrderSubject {
            get {
                return ResourceManager.GetString("WorkOrderSubject", resourceCulture);
            }
        }
    }
}
