//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedOrganization
    {
        public int id { get; set; }
        public int user_Id { get; set; }
        public int organization_Id { get; set; }
        public bool isDefault { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}
