//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int id { get; set; }
        public int budgetType_Id { get; set; }
        public string title { get; set; }
        public decimal amount { get; set; }
        public string description { get; set; }
        public bool visibility { get; set; }
        public System.DateTime createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
    }
}
