//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessFile
    {
        public int id { get; set; }
        public int business_Id { get; set; }
        public int fileType_Id { get; set; }
        public string name { get; set; }
        public string urlPath { get; set; }
        public string description { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual ModuleItem ModuleItem { get; set; }
    }
}
