//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessOther
    {
        public int id { get; set; }
        public int business_Id { get; set; }
        public Nullable<decimal> bumiShare { get; set; }
        public Nullable<decimal> nonBumiShare { get; set; }
        public Nullable<decimal> foreignShare { get; set; }
        public Nullable<decimal> bumiCapital { get; set; }
        public Nullable<bool> classA { get; set; }
        public Nullable<bool> classB { get; set; }
        public Nullable<bool> classBX { get; set; }
        public Nullable<bool> classC { get; set; }
        public Nullable<bool> classD { get; set; }
        public Nullable<bool> classE { get; set; }
        public Nullable<bool> classEX { get; set; }
        public Nullable<bool> classF { get; set; }
        public Nullable<bool> pkk { get; set; }
        public Nullable<bool> tnb { get; set; }
        public Nullable<bool> jba { get; set; }
        public Nullable<bool> mara { get; set; }
        public Nullable<bool> jkr { get; set; }
        public Nullable<bool> dbkl { get; set; }
        public Nullable<bool> financeMinistry { get; set; }
        public Nullable<bool> jkh { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
