//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessWorkCategory
    {
        public int Id { get; set; }
        public int business_Id { get; set; }
        public int workCategory_Id { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual WorkCategory WorkCategory { get; set; }
    }
}
