//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.AssignedBusinesses = new HashSet<AssignedBusiness>();
            this.BusinessAddresses = new HashSet<BusinessAddress>();
            this.BusinessClassifications = new HashSet<BusinessClassification>();
            this.BusinessFiles = new HashSet<BusinessFile>();
            this.BusinessOrganizations = new HashSet<BusinessOrganization>();
            this.BusinessOthers = new HashSet<BusinessOther>();
            this.BusinessWorkCategories = new HashSet<BusinessWorkCategory>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public int businessType_Id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string webSite { get; set; }
        public string primaryContact { get; set; }
        public string primaryEmail { get; set; }
        public Nullable<int> primaryCurrency { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> isMAHBRegistered { get; set; }
        public string registrationNo { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string referenceId { get; set; }
        public string rocNo { get; set; }
        public string businessCategory { get; set; }
        public Nullable<int> paidUpCapital { get; set; }
        public Nullable<int> companyType { get; set; }
        public string address { get; set; }
        public string limitation { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> profileLastUpdated { get; set; }
        public string gstNo { get; set; }
    
        public virtual ICollection<AssignedBusiness> AssignedBusinesses { get; set; }
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual ModuleItem ModuleItem1 { get; set; }
        public virtual ICollection<BusinessAddress> BusinessAddresses { get; set; }
        public virtual ICollection<BusinessClassification> BusinessClassifications { get; set; }
        public virtual ICollection<BusinessFile> BusinessFiles { get; set; }
        public virtual ICollection<BusinessOrganization> BusinessOrganizations { get; set; }
        public virtual ICollection<BusinessOther> BusinessOthers { get; set; }
        public virtual ICollection<BusinessWorkCategory> BusinessWorkCategories { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
