//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public CompanyProfile()
        {
            this.Leave_View_Apply = new HashSet<Leave_View_Apply>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<decimal> totalCapital { get; set; }
        public Nullable<int> companyType_Id { get; set; }
        public Nullable<int> noOfUser { get; set; }
        public Nullable<int> service_Id { get; set; }
        public string phoneNo { get; set; }
        public string emailAddress { get; set; }
        public System.DateTime effectiveDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<decimal> totalRevenue { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual ModuleItem ModuleItem1 { get; set; }
        public virtual ICollection<Leave_View_Apply> Leave_View_Apply { get; set; }
    }
}
