//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroupPriceList
    {
        public int id { get; set; }
        public string sysRowID { get; set; }
        public string company { get; set; }
        public string groupCode { get; set; }
        public string seqNum { get; set; }
        public string listCode { get; set; }
    }
}
