//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPriceList
    {
        public Nullable<int> CustNum { get; set; }
        public string ShipToNum { get; set; }
        public Nullable<int> SeqNum { get; set; }
        public string ListCode { get; set; }
        public int id { get; set; }
        public string sysRowID { get; set; }
    }
}
