//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ShipToAddress = new HashSet<ShipToAddress>();
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string custID { get; set; }
        public string address3 { get; set; }
        public string groupCode { get; set; }
        public string Company { get; set; }
        public string tin { get; set; }
        public Nullable<bool> creditHold { get; set; }
    
        public virtual ICollection<ShipToAddress> ShipToAddress { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
