//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardCategory
    {
        public DashboardCategory()
        {
            this.DashboardCategory1 = new HashSet<DashboardCategory>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_Id { get; set; }
        public Nullable<int> menu_Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string icon { get; set; }
        public string backColor { get; set; }
        public string fontColor { get; set; }
        public int ordering { get; set; }
        public bool visibility { get; set; }
    
        public virtual ICollection<DashboardCategory> DashboardCategory1 { get; set; }
        public virtual DashboardCategory DashboardCategory2 { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
