//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string company { get; set; }
        public string districtID { get; set; }
        public string districtDesc { get; set; }
        public string sysRowID { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
