//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailScheduled
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string emailContent { get; set; }
        public string emailTo { get; set; }
        public string emailCC { get; set; }
        public string filePath { get; set; }
        public string fileName { get; set; }
        public string status_Id { get; set; }
        public string remark { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
