//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Carry_Forward
    {
        public int id { get; set; }
        public Nullable<int> Moduleitem_LeaveType_Id { get; set; }
        public Nullable<int> Moduleitem_Jobgrade_Id { get; set; }
        public Nullable<int> Moduleitem_LeaveCarryForwardMethod_Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual ModuleItem ModuleItem1 { get; set; }
        public virtual ModuleItem ModuleItem2 { get; set; }
    }
}
