//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_View_Apply
    {
        public int id { get; set; }
        public int Company_Profile_Id { get; set; }
        public int UserRole_Id { get; set; }
        public Nullable<int> Moduleitem_LeaveType_Id { get; set; }
        public Nullable<int> Moduleitem_LeaveViewStatus_Id { get; set; }
        public Nullable<int> Moduleitem_LeaveApplyStatus_Id { get; set; }
        public Nullable<int> Moduleitem_LeaveCancelStatus_Id { get; set; }
    
        public virtual CompanyProfile CompanyProfile { get; set; }
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual ModuleItem ModuleItem1 { get; set; }
        public virtual ModuleItem ModuleItem2 { get; set; }
        public virtual ModuleItem ModuleItem3 { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
