//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizationSection
    {
        public LocalizationSection()
        {
            this.LocalizationResources = new HashSet<LocalizationResource>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string sector { get; set; }
    
        public virtual ICollection<LocalizationResource> LocalizationResources { get; set; }
    }
}
