//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LooseBarcodeSetting
    {
        public int id { get; set; }
        public Nullable<int> barcodeFromPos { get; set; }
        public Nullable<int> barcodeToPos { get; set; }
        public Nullable<int> weightFromPos { get; set; }
        public Nullable<int> weightToPos { get; set; }
        public Nullable<decimal> weightMutiply { get; set; }
        public Nullable<int> barcodeLength { get; set; }
    }
}
