//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class LooseConversionItem
    {
        public int id { get; set; }
        public Nullable<int> looseConversion_Id { get; set; }
        public Nullable<int> weighScaleBarcode_Id { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> LooseQty { get; set; }
        public Nullable<decimal> RunningBalance { get; set; }
    
        public virtual LooseConversion LooseConversion { get; set; }
        public virtual ProductWeightBarcode ProductWeightBarcode { get; set; }
    }
}
