//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.DashboardCategories = new HashSet<DashboardCategory>();
            this.MenuItem1 = new HashSet<MenuItem>();
            this.ModuleCodes = new HashSet<ModuleCode>();
            this.TableProfiles = new HashSet<TableProfile>();
            this.UserRights = new HashSet<UserRight>();
        }
    
        public int id { get; set; }
        public Nullable<int> reference_Id { get; set; }
        public string name { get; set; }
        public string pageName { get; set; }
        public string pageUrl { get; set; }
        public string imageUrl { get; set; }
        public Nullable<int> ordering { get; set; }
        public Nullable<int> menuType_Id { get; set; }
        public Nullable<int> menuLevel_Id { get; set; }
        public Nullable<int> reportCategory_Id { get; set; }
        public bool visibility { get; set; }
        public bool isActive { get; set; }
        public bool showAsMain { get; set; }
    
        public virtual ICollection<DashboardCategory> DashboardCategories { get; set; }
        public virtual ICollection<MenuItem> MenuItem1 { get; set; }
        public virtual MenuItem MenuItem2 { get; set; }
        public virtual ICollection<ModuleCode> ModuleCodes { get; set; }
        public virtual ICollection<TableProfile> TableProfiles { get; set; }
        public virtual ICollection<UserRight> UserRights { get; set; }
    }
}
