//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleType
    {
        public ModuleType()
        {
            this.ModuleItems = new HashSet<ModuleItem>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool visibility { get; set; }
    
        public virtual ICollection<ModuleItem> ModuleItems { get; set; }
    }
}
