//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemDeleted
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public int orderLine { get; set; }
        public string partNum { get; set; }
        public string lineDesc { get; set; }
        public string ium { get; set; }
        public string salesUm { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public decimal orderQty { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> listPrice { get; set; }
        public Nullable<int> product_Id { get; set; }
        public Nullable<int> QtyType_ModuleItem_Id { get; set; }
        public Nullable<int> OrderUOM_Id { get; set; }
        public Nullable<int> operationStyle_ModuleItem_Id { get; set; }
        public Nullable<decimal> operationCost { get; set; }
        public Nullable<int> complimentary_ModuleItem_Id { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> scannedQty { get; set; }
        public Nullable<bool> allowVaryWeight { get; set; }
        public Nullable<decimal> originalUnitPrice { get; set; }
        public Nullable<decimal> finalQty { get; set; }
        public Nullable<int> orderItemId { get; set; }
        public Nullable<bool> IsItemReturned { get; set; }
        public Nullable<decimal> avlQty { get; set; }
        public string scannedLabel { get; set; }
        public Nullable<decimal> realOriginalUnitPrice { get; set; }
        public Nullable<decimal> actualOperationCost { get; set; }
        public Nullable<int> deletedBy { get; set; }
        public Nullable<System.DateTime> deletedAt { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<decimal> discountPer { get; set; }
        public Nullable<decimal> discountAmt { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual ModuleItem ModuleItem1 { get; set; }
        public virtual ModuleItem ModuleItem2 { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderUOM OrderUOM { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
