//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemDiscountApproval
    {
        public int id { get; set; }
        public int orderItem_Id { get; set; }
        public decimal discount { get; set; }
        public int approverUser_Id { get; set; }
        public Nullable<System.DateTime> approvalDate { get; set; }
        public string remarks { get; set; }
        public int requester_Id { get; set; }
        public Nullable<int> orderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
