//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderUOM
    {
        public OrderUOM()
        {
            this.OrderItemDeleted = new HashSet<OrderItemDeleted>();
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<bool> disableLooseQty { get; set; }
        public Nullable<bool> disableFullQty { get; set; }
        public Nullable<bool> defaultLooseQty { get; set; }
    
        public virtual ICollection<OrderItemDeleted> OrderItemDeleted { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
