//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int id { get; set; }
        public int order_Id { get; set; }
        public string paymentType { get; set; }
        public decimal amount { get; set; }
        public string refNumber { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string paymentStatus { get; set; }
        public string Bank { get; set; }
        public int user_Id { get; set; }
        public Nullable<bool> IsRefund { get; set; }
    
        public virtual User User { get; set; }
        public virtual Order Order { get; set; }
    }
}
