//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderApproval
    {
        public int id { get; set; }
        public int order_Id { get; set; }
        public int submittedUser_Id { get; set; }
        public System.DateTime submittedDate { get; set; }
        public string approvalStatus { get; set; }
        public string remarks { get; set; }
        public Nullable<int> approvedUser_Id { get; set; }
        public Nullable<System.DateTime> approvedDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
