//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationCategory
    {
        public OrganizationCategory()
        {
            this.Organizations = new HashSet<Organization>();
            this.OrganizationCategoryConfigs = new HashSet<OrganizationCategoryConfig>();
            this.OrganizationCategoryConfigs1 = new HashSet<OrganizationCategoryConfig>();
        }
    
        public int id { get; set; }
        public string categoryName { get; set; }
        public bool isChildNodeAllowed { get; set; }
        public string backColor { get; set; }
        public string imageUrl { get; set; }
        public bool isActive { get; set; }
        public string forceColor { get; set; }
        public int ordring { get; set; }
    
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<OrganizationCategoryConfig> OrganizationCategoryConfigs { get; set; }
        public virtual ICollection<OrganizationCategoryConfig> OrganizationCategoryConfigs1 { get; set; }
    }
}
