//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.AdhocReports = new HashSet<AdhocReport>();
            this.AssignedOrganizations = new HashSet<AssignedOrganization>();
            this.BusinessOrganizations = new HashSet<BusinessOrganization>();
            this.CalendarEvents = new HashSet<CalendarEvent>();
            this.HelpDesks = new HashSet<HelpDesk>();
            this.Organization1 = new HashSet<Organization>();
            this.OrganizationEmails = new HashSet<OrganizationEmail>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_Id { get; set; }
        public int orgCategory_Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string prefix { get; set; }
        public bool isActive { get; set; }
        public string code { get; set; }
        public string sapcode { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ICollection<AdhocReport> AdhocReports { get; set; }
        public virtual ICollection<AssignedOrganization> AssignedOrganizations { get; set; }
        public virtual ICollection<BusinessOrganization> BusinessOrganizations { get; set; }
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
        public virtual ICollection<HelpDesk> HelpDesks { get; set; }
        public virtual ICollection<Organization> Organization1 { get; set; }
        public virtual Organization Organization2 { get; set; }
        public virtual OrganizationCategory OrganizationCategory { get; set; }
        public virtual ICollection<OrganizationEmail> OrganizationEmails { get; set; }
    }
}
