//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationEmail
    {
        public int id { get; set; }
        public int organization_Id { get; set; }
        public int department_Id { get; set; }
        public string emailTo { get; set; }
        public string emailFrom { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string smtp { get; set; }
        public int smptPort { get; set; }
        public bool isSSL { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
