//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReport
    {
        public int id { get; set; }
        public System.DateTime paymentDate { get; set; }
        public decimal epiCashEntryTotal { get; set; }
        public int epicorCountOfSalesOrders { get; set; }
        public decimal totalCash { get; set; }
        public decimal totalCreditCard { get; set; }
        public decimal totalCheque { get; set; }
        public decimal totalAdvanceCash { get; set; }
        public decimal totalAdvanceCreditCard { get; set; }
        public decimal totalAdvanceCheque { get; set; }
        public int totalEntries { get; set; }
        public Nullable<decimal> totalDiscount { get; set; }
        public Nullable<decimal> epiAdvanceEntryTotal { get; set; }
    }
}
