//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSOrderNumber
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int LastRunningNumber { get; set; }
        public bool IsActive { get; set; }
    }
}
