//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCarton
    {
        public ProductCarton()
        {
            this.LooseConversion = new HashSet<LooseConversion>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> productKey { get; set; }
        public string epicorPartNo { get; set; }
        public string barcode { get; set; }
        public string vendorProductCode { get; set; }
        public Nullable<decimal> productBarcodeLength { get; set; }
        public Nullable<decimal> productCodeFromPosition { get; set; }
        public Nullable<decimal> productCodeToPosition { get; set; }
        public Nullable<decimal> weightFromPosition { get; set; }
        public Nullable<decimal> weightToPosition { get; set; }
        public string weightValue { get; set; }
        public Nullable<decimal> weightMutiplier { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> CtnQty { get; set; }
        public Nullable<decimal> PickedCtnQty { get; set; }
        public Nullable<bool> IsPickedComplete { get; set; }
        public Nullable<bool> IsCarton { get; set; }
        public Nullable<bool> IsPartialCarton { get; set; }
        public Nullable<decimal> IumQty { get; set; }
        public string Ium { get; set; }
        public Nullable<decimal> LooseQty { get; set; }
        public string LooseUom { get; set; }
        public Nullable<bool> IsVaryWg { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<long> SeqNum { get; set; }
        public Nullable<bool> OnHold { get; set; }
        public Nullable<System.DateTime> PickedCompletedDate { get; set; }
        public Nullable<int> PickedOrderId { get; set; }
        public Nullable<int> PickedOrderItemId { get; set; }
        public Nullable<System.DateTime> PickedLastModifiedDate { get; set; }
        public Nullable<bool> IsPickStatusToSync { get; set; }
    
        public virtual ICollection<LooseConversion> LooseConversion { get; set; }
    }
}
