//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderItemDeleted = new HashSet<OrderItemDeleted>();
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int id { get; set; }
        public string partNumber { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public string ProdGrup_Description { get; set; }
        public string Part_ClassID { get; set; }
        public string PartClass_Description { get; set; }
        public string Country_Description { get; set; }
        public string UOMClass_DefUomCode { get; set; }
        public string Part_SalesUM { get; set; }
        public string Part_IUM { get; set; }
        public string UOMClass_BaseUOMCode { get; set; }
        public Nullable<int> Country_CountryNum { get; set; }
        public string UOMClass_ClassType { get; set; }
        public string UOMClass_Description { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Company { get; set; }
        public string Part_ShortChar01_Temprature_Type_Code { get; set; }
        public string Part_RefCategory_Item_Brand_Code { get; set; }
        public string UD04_Character01_Item_Brand { get; set; }
        public Nullable<bool> Part_CheckBox01_Allow_Selling_Loose { get; set; }
        public Nullable<bool> AllowSellingVaryWeight { get; set; }
        public Nullable<bool> UOMConv_ConvFactor { get; set; }
        public Nullable<bool> Part_CheckBox03_Slice { get; set; }
        public Nullable<bool> Part_CheckBox04_Cube { get; set; }
        public string Part_ShortChar03_LooseUOM { get; set; }
        public Nullable<bool> Part_CheckBox05_Standard_Full_Qty { get; set; }
        public Nullable<bool> Part_RunOut { get; set; }
        public Nullable<bool> Part_InActive { get; set; }
        public Nullable<bool> Part_OnHold { get; set; }
        public Nullable<bool> Part_CheckBox13_Strip { get; set; }
        public string Part_Character04_Generic_Code { get; set; }
        public Nullable<decimal> Part_Number03_Avg_Weight { get; set; }
        public string itemBrandCode { get; set; }
        public string syncId { get; set; }
        public Nullable<bool> inActive { get; set; }
        public Nullable<decimal> conversionFactor { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
    
        public virtual ICollection<OrderItemDeleted> OrderItemDeleted { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
