//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWeightBarcode
    {
        public ProductWeightBarcode()
        {
            this.LooseConversionItem = new HashSet<LooseConversionItem>();
        }
    
        public int id { get; set; }
        public string epicorePartNo { get; set; }
        public string description { get; set; }
        public string fullBarcode { get; set; }
        public string barcode { get; set; }
        public string barcodeFromPos { get; set; }
        public string barcodeToPos { get; set; }
        public string weightFromPos { get; set; }
        public string weightToPos { get; set; }
        public Nullable<decimal> weightMultiply { get; set; }
        public string barcodeLength { get; set; }
        public string offSet1 { get; set; }
        public string offSet2 { get; set; }
        public string weightValue { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> StdLooseQty { get; set; }
        public string StdLooseUom { get; set; }
        public Nullable<decimal> PickedStdLooseQty { get; set; }
        public Nullable<bool> IsPickedComplete { get; set; }
    
        public virtual ICollection<LooseConversionItem> LooseConversionItem { get; set; }
    }
}
