//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningCode
    {
        public int id { get; set; }
        public string moduleName { get; set; }
        public string prefix { get; set; }
        public Nullable<int> organization_Id { get; set; }
        public Nullable<int> runningNo { get; set; }
        public Nullable<int> module_Id { get; set; }
        public Nullable<int> runningId { get; set; }
    }
}
