//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerSetting
    {
        public int id { get; set; }
        public int syncModule_Id { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public int timeSlot { get; set; }
        public Nullable<bool> isActive { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
    }
}
