//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerLog
    {
        public int id { get; set; }
        public int schedulerSetting_Id { get; set; }
        public System.DateTime startDateTime { get; set; }
        public Nullable<System.DateTime> endDateTime { get; set; }
        public Nullable<bool> result { get; set; }
        public Nullable<int> totalRecordProcessed { get; set; }
        public string errorMessage { get; set; }
    }
}
