//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalanceView
    {
        public string partNum { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> onHandQty { get; set; }
        public decimal totalQtyBeforePayment { get; set; }
        public decimal totalQtyAfterPayment { get; set; }
        public Nullable<decimal> remainingQty { get; set; }
    }
}
