//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalance
    {
        public int id { get; set; }
        public string company { get; set; }
        public string partNum { get; set; }
        public string warehouseCode { get; set; }
        public string uom { get; set; }
        public decimal onHandQty { get; set; }
        public string uniqueField { get; set; }
        public string Freezer { get; set; }
        public string Row { get; set; }
        public string Column { get; set; }
        public string Level { get; set; }
        public string Location { get; set; }
    }
}
