//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProfileMetadataList
    {
        public TableProfileMetadataList()
        {
            this.TableProfileMetadataList1 = new HashSet<TableProfileMetadataList>();
            this.TableProfileMetadataListValues = new HashSet<TableProfileMetadataListValue>();
        }
    
        public int tableProfileMetadata_Id { get; set; }
        public Nullable<int> parent_Id { get; set; }
        public bool isMultiValue { get; set; }
        public Nullable<int> lookUpValue { get; set; }
        public Nullable<int> lookDefaultValue { get; set; }
        public string dataRetrieveURL { get; set; }
    
        public virtual TableProfileMetadata TableProfileMetadata { get; set; }
        public virtual ICollection<TableProfileMetadataList> TableProfileMetadataList1 { get; set; }
        public virtual TableProfileMetadataList TableProfileMetadataList2 { get; set; }
        public virtual ICollection<TableProfileMetadataListValue> TableProfileMetadataListValues { get; set; }
    }
}
