//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProfileMetadataListValue
    {
        public int id { get; set; }
        public int tableProfileMetadataList_Id { get; set; }
        public string fieldText { get; set; }
        public bool visibility { get; set; }
    
        public virtual TableProfileMetadataList TableProfileMetadataList { get; set; }
    }
}
