//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProfileMetadata
    {
        public int id { get; set; }
        public int tableProfile_Id { get; set; }
        public string fieldName { get; set; }
        public string valueFieldName { get; set; }
        public int localizationResourceForGrid_Id { get; set; }
        public bool isMandatory { get; set; }
        public bool visibilityInGridView { get; set; }
        public bool visibilityInCreate { get; set; }
        public bool isEditableInCreate { get; set; }
        public bool visibilityInEdit { get; set; }
        public bool isEditableInEdit { get; set; }
        public string templateName { get; set; }
        public bool visibility { get; set; }
        public string validationRule { get; set; }
        public int sortOrder { get; set; }
    
        public virtual LocalizationResource LocalizationResource { get; set; }
        public virtual TableProfile TableProfile { get; set; }
        public virtual TableProfileMetadataBool TableProfileMetadataBool { get; set; }
        public virtual TableProfileMetadataDateTime TableProfileMetadataDateTime { get; set; }
        public virtual TableProfileMetadataDecimal TableProfileMetadataDecimal { get; set; }
        public virtual TableProfileMetadataInteger TableProfileMetadataInteger { get; set; }
        public virtual TableProfileMetadataList TableProfileMetadataList { get; set; }
        public virtual TableProfileMetadataMultiFileUpload TableProfileMetadataMultiFileUpload { get; set; }
        public virtual TableProfileMetadataSingleFileUpload TableProfileMetadataSingleFileUpload { get; set; }
        public virtual TableProfileMetadataText TableProfileMetadataText { get; set; }
    }
}
