//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProfile
    {
        public TableProfile()
        {
            this.TableProfile1 = new HashSet<TableProfile>();
            this.TableProfileMetadatas = new HashSet<TableProfileMetadata>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> menu_Id { get; set; }
        public Nullable<int> parent_Id { get; set; }
        public string url { get; set; }
        public int localizationResource_Id { get; set; }
        public string icon { get; set; }
        public int sortOrder { get; set; }
        public bool visibility { get; set; }
    
        public virtual LocalizationResource LocalizationResource { get; set; }
        public virtual MenuItem MenuItem { get; set; }
        public virtual ICollection<TableProfile> TableProfile1 { get; set; }
        public virtual TableProfile TableProfile2 { get; set; }
        public virtual ICollection<TableProfileMetadata> TableProfileMetadatas { get; set; }
    }
}
