//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProfileMetadataDateTime
    {
        public int tableProfileMetadata_Id { get; set; }
        public Nullable<System.DateTime> minDate { get; set; }
        public Nullable<System.DateTime> maxDate { get; set; }
        public Nullable<bool> isAllowPastDate { get; set; }
        public Nullable<bool> isFollowCalendarSetting { get; set; }
        public Nullable<bool> isCurrentDateDefault { get; set; }
    
        public virtual TableProfileMetadata TableProfileMetadata { get; set; }
    }
}
