//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AssignedBusinesses = new HashSet<AssignedBusiness>();
            this.AssignedOrganizations = new HashSet<AssignedOrganization>();
            this.FileUploadHistories = new HashSet<FileUploadHistory>();
            this.HelpDesks = new HashSet<HelpDesk>();
            this.OrderPayments = new HashSet<OrderPayment>();
            this.OrderUpdates = new HashSet<OrderUpdate>();
            this.UserRoles = new HashSet<UserRole>();
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
            this.OrderApproval = new HashSet<OrderApproval>();
            this.OrderApproval1 = new HashSet<OrderApproval>();
            this.OrderItemDeleted = new HashSet<OrderItemDeleted>();
            this.OrderItemDeleted1 = new HashSet<OrderItemDeleted>();
            this.OrderItemDiscountApproval = new HashSet<OrderItemDiscountApproval>();
            this.OrderItemDiscountApproval1 = new HashSet<OrderItemDiscountApproval>();
            this.OrderItems = new HashSet<OrderItems>();
            this.OrderItemScanned = new HashSet<OrderItemScanned>();
        }
    
        public int id { get; set; }
        public int userRole_Id { get; set; }
        public Nullable<int> bussiness_Id { get; set; }
        public Nullable<int> bussinessType_Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string userName { get; set; }
        public string passwordHash { get; set; }
        public Nullable<bool> verified { get; set; }
        public Nullable<int> language { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string status { get; set; }
        public Nullable<bool> isTermsAccepted { get; set; }
        public string address { get; set; }
        public string employeeNo { get; set; }
        public string department { get; set; }
        public string jobTitle { get; set; }
        public string mobileNo { get; set; }
        public string officeNo { get; set; }
        public string salaryId { get; set; }
        public Nullable<int> gred { get; set; }
        public string idNo { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<int> age { get; set; }
        public string accountNo { get; set; }
        public Nullable<int> bankId { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> employeegroupId { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public Nullable<System.DateTime> expireddate { get; set; }
        public Nullable<decimal> yearofservice { get; set; }
        public Nullable<bool> isAccessAllOrganization { get; set; }
        public string profileImageName { get; set; }
    
        public virtual ICollection<AssignedBusiness> AssignedBusinesses { get; set; }
        public virtual ICollection<AssignedOrganization> AssignedOrganizations { get; set; }
        public virtual Business Business { get; set; }
        public virtual ICollection<FileUploadHistory> FileUploadHistories { get; set; }
        public virtual ICollection<HelpDesk> HelpDesks { get; set; }
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        public virtual ICollection<OrderUpdate> OrderUpdates { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
        public virtual ICollection<OrderApproval> OrderApproval { get; set; }
        public virtual ICollection<OrderApproval> OrderApproval1 { get; set; }
        public virtual ICollection<OrderItemDeleted> OrderItemDeleted { get; set; }
        public virtual ICollection<OrderItemDeleted> OrderItemDeleted1 { get; set; }
        public virtual ICollection<OrderItemDiscountApproval> OrderItemDiscountApproval { get; set; }
        public virtual ICollection<OrderItemDiscountApproval> OrderItemDiscountApproval1 { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<OrderItemScanned> OrderItemScanned { get; set; }
    }
}
