//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanodale.Entity.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.UserRights = new HashSet<UserRight>();
            this.Leave_View_Apply = new HashSet<Leave_View_Apply>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public int user_Id { get; set; }
        public string roleName { get; set; }
        public string description { get; set; }
        public bool isAdmin { get; set; }
        public bool status { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string landingPage { get; set; }
    
        public virtual ICollection<UserRight> UserRights { get; set; }
        public virtual ICollection<Leave_View_Apply> Leave_View_Apply { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual User User { get; set; }
    }
}
