// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Hanodale.WebUI.Controllers
{
    public partial class DashboardController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DashboardController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Dashboard()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Dashboard);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DashboardController Actions { get { return MVC.Dashboard; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Dashboard";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Dashboard";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string MyNotifications = "MyNotifications";
            public readonly string UserInfoNav = "UserInfoNav";
            public readonly string Index = "Index";
            public readonly string Dashboard = "Dashboard";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string MyNotifications = "MyNotifications";
            public const string UserInfoNav = "UserInfoNav";
            public const string Index = "Index";
            public const string Dashboard = "Dashboard";
        }


        static readonly ActionParamsClass_Dashboard s_params_Dashboard = new ActionParamsClass_Dashboard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Dashboard DashboardParams { get { return s_params_Dashboard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Dashboard
        {
            public readonly string dashboardBoxName = "dashboardBoxName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AssetBreakdown = "_AssetBreakdown";
                public readonly string _Index = "_Index";
                public readonly string _NotificationBody = "_NotificationBody";
                public readonly string _Purchase = "_Purchase";
                public readonly string _RFQDashboard = "_RFQDashboard";
                public readonly string _RFQStatistic = "_RFQStatistic";
                public readonly string _SearchPanel = "_SearchPanel";
                public readonly string _UserInfoNav = "_UserInfoNav";
                public readonly string _WorkOrder = "_WorkOrder";
                public readonly string Index = "Index";
            }
            public readonly string _AssetBreakdown = "~/Views/Dashboard/_AssetBreakdown.cshtml";
            public readonly string _Index = "~/Views/Dashboard/_Index.cshtml";
            public readonly string _NotificationBody = "~/Views/Dashboard/_NotificationBody.cshtml";
            public readonly string _Purchase = "~/Views/Dashboard/_Purchase.cshtml";
            public readonly string _RFQDashboard = "~/Views/Dashboard/_RFQDashboard.cshtml";
            public readonly string _RFQStatistic = "~/Views/Dashboard/_RFQStatistic.cshtml";
            public readonly string _SearchPanel = "~/Views/Dashboard/_SearchPanel.cshtml";
            public readonly string _UserInfoNav = "~/Views/Dashboard/_UserInfoNav.cshtml";
            public readonly string _WorkOrder = "~/Views/Dashboard/_WorkOrder.cshtml";
            public readonly string Index = "~/Views/Dashboard/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DashboardController : Hanodale.WebUI.Controllers.DashboardController
    {
        public T4MVC_DashboardController() : base(Dummy.Instance) { }

        [NonAction]
        partial void MyNotificationsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult MyNotifications()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.MyNotifications);
            MyNotificationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UserInfoNavOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserInfoNav()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserInfoNav);
            UserInfoNavOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DashboardOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string dashboardBoxName);

        [NonAction]
        public override System.Web.Mvc.JsonResult Dashboard(string dashboardBoxName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Dashboard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dashboardBoxName", dashboardBoxName);
            DashboardOverride(callInfo, dashboardBoxName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
