// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Hanodale.WebUI.Controllers
{
    public partial class HelpDeskController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HelpDeskController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BindHelpDesk()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BindHelpDesk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveHelpDesk()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveHelpDesk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveApprovalHelpDesk()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveApprovalHelpDesk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Check()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Check);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CallBack()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CallBack);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveCallBackHelpDesk()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveCallBackHelpDesk);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFile);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HelpDeskController Actions { get { return MVC.HelpDesk; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "HelpDesk";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "HelpDesk";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string BindHelpDesk = "BindHelpDesk";
            public readonly string RenderAction = "RenderAction";
            public readonly string GetCustomSearchPanel = "GetCustomSearchPanel";
            public readonly string Create = "Create";
            public readonly string SaveHelpDesk = "SaveHelpDesk";
            public readonly string SaveApprovalHelpDesk = "SaveApprovalHelpDesk";
            public readonly string Edit = "Edit";
            public readonly string Check = "Check";
            public readonly string Delete = "Delete";
            public readonly string CallBack = "CallBack";
            public readonly string SaveCallBackHelpDesk = "SaveCallBackHelpDesk";
            public readonly string GetFile = "GetFile";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string BindHelpDesk = "BindHelpDesk";
            public const string RenderAction = "RenderAction";
            public const string GetCustomSearchPanel = "GetCustomSearchPanel";
            public const string Create = "Create";
            public const string SaveHelpDesk = "SaveHelpDesk";
            public const string SaveApprovalHelpDesk = "SaveApprovalHelpDesk";
            public const string Edit = "Edit";
            public const string Check = "Check";
            public const string Delete = "Delete";
            public const string CallBack = "CallBack";
            public const string SaveCallBackHelpDesk = "SaveCallBackHelpDesk";
            public const string GetFile = "GetFile";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string search = "search";
        }
        static readonly ActionParamsClass_BindHelpDesk s_params_BindHelpDesk = new ActionParamsClass_BindHelpDesk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BindHelpDesk BindHelpDeskParams { get { return s_params_BindHelpDesk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BindHelpDesk
        {
            public readonly string param = "param";
            public readonly string myKey = "myKey";
        }
        static readonly ActionParamsClass_SaveHelpDesk s_params_SaveHelpDesk = new ActionParamsClass_SaveHelpDesk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveHelpDesk SaveHelpDeskParams { get { return s_params_SaveHelpDesk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveHelpDesk
        {
            public readonly string model = "model";
            public readonly string fileUpload = "fileUpload";
        }
        static readonly ActionParamsClass_SaveApprovalHelpDesk s_params_SaveApprovalHelpDesk = new ActionParamsClass_SaveApprovalHelpDesk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveApprovalHelpDesk SaveApprovalHelpDeskParams { get { return s_params_SaveApprovalHelpDesk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveApprovalHelpDesk
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
            public readonly string readOnly = "readOnly";
            public readonly string hideBackButton = "hideBackButton";
        }
        static readonly ActionParamsClass_Check s_params_Check = new ActionParamsClass_Check();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Check CheckParams { get { return s_params_Check; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Check
        {
            public readonly string id = "id";
            public readonly string readOnly = "readOnly";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_CallBack s_params_CallBack = new ActionParamsClass_CallBack();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CallBack CallBackParams { get { return s_params_CallBack; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CallBack
        {
            public readonly string id = "id";
            public readonly string readOnly = "readOnly";
        }
        static readonly ActionParamsClass_SaveCallBackHelpDesk s_params_SaveCallBackHelpDesk = new ActionParamsClass_SaveCallBackHelpDesk();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveCallBackHelpDesk SaveCallBackHelpDeskParams { get { return s_params_SaveCallBackHelpDesk; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveCallBackHelpDesk
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetFile s_params_GetFile = new ActionParamsClass_GetFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFile GetFileParams { get { return s_params_GetFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFile
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _SearchPanel = "_SearchPanel";
                public readonly string CallBack = "CallBack";
                public readonly string Create = "Create";
                public readonly string Index = "Index";
                public readonly string RenderAction = "RenderAction";
                public readonly string UpdateStatus = "UpdateStatus";
            }
            public readonly string _SearchPanel = "~/Views/HelpDesk/_SearchPanel.cshtml";
            public readonly string CallBack = "~/Views/HelpDesk/CallBack.cshtml";
            public readonly string Create = "~/Views/HelpDesk/Create.cshtml";
            public readonly string Index = "~/Views/HelpDesk/Index.cshtml";
            public readonly string RenderAction = "~/Views/HelpDesk/RenderAction.cshtml";
            public readonly string UpdateStatus = "~/Views/HelpDesk/UpdateStatus.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HelpDeskController : Hanodale.WebUI.Controllers.HelpDeskController
    {
        public T4MVC_HelpDeskController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string search);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(string search)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            IndexOverride(callInfo, search);
            return callInfo;
        }

        [NonAction]
        partial void BindHelpDeskOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Hanodale.WebUI.Models.DataTableModel param, string myKey);

        [NonAction]
        public override System.Web.Mvc.ActionResult BindHelpDesk(Hanodale.WebUI.Models.DataTableModel param, string myKey)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BindHelpDesk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "myKey", myKey);
            BindHelpDeskOverride(callInfo, param, myKey);
            return callInfo;
        }

        [NonAction]
        partial void RenderActionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult RenderAction()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RenderAction);
            RenderActionOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCustomSearchPanelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetCustomSearchPanel()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetCustomSearchPanel);
            GetCustomSearchPanelOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveHelpDeskOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Hanodale.WebUI.Models.HelpDeskModel model, System.Collections.Generic.List<System.Web.HttpPostedFileBase> fileUpload);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveHelpDesk(Hanodale.WebUI.Models.HelpDeskModel model, System.Collections.Generic.List<System.Web.HttpPostedFileBase> fileUpload)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveHelpDesk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileUpload", fileUpload);
            SaveHelpDeskOverride(callInfo, model, fileUpload);
            return callInfo;
        }

        [NonAction]
        partial void SaveApprovalHelpDeskOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Hanodale.WebUI.Models.HelpDeskModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveApprovalHelpDesk(Hanodale.WebUI.Models.HelpDeskModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveApprovalHelpDesk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveApprovalHelpDeskOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, bool readOnly, bool hideBackButton);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(string id, bool readOnly, bool hideBackButton)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "readOnly", readOnly);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hideBackButton", hideBackButton);
            EditOverride(callInfo, id, readOnly, hideBackButton);
            return callInfo;
        }

        [NonAction]
        partial void CheckOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id, bool readOnly);

        [NonAction]
        public override System.Web.Mvc.JsonResult Check(string id, bool readOnly)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Check);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "readOnly", readOnly);
            CheckOverride(callInfo, id, readOnly);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CallBackOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string id, bool readOnly);

        [NonAction]
        public override System.Web.Mvc.JsonResult CallBack(string id, bool readOnly)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CallBack);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "readOnly", readOnly);
            CallBackOverride(callInfo, id, readOnly);
            return callInfo;
        }

        [NonAction]
        partial void SaveCallBackHelpDeskOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Hanodale.WebUI.Models.HelpDeskModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveCallBackHelpDesk(Hanodale.WebUI.Models.HelpDeskModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveCallBackHelpDesk);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveCallBackHelpDeskOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetFile(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetFileOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
