// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AccessDenied = "_AccessDenied";
                public readonly string _ButtonPartial = "_ButtonPartial";
                public readonly string _ColumnFilter = "_ColumnFilter";
                public readonly string _ContainerSettings = "_ContainerSettings";
                public readonly string _GuestLayout = "_GuestLayout";
                public readonly string _LanguageSection = "_LanguageSection";
                public readonly string _Layout = "_Layout";
                public readonly string _LoginLayout = "_LoginLayout";
                public readonly string _MenuPartial = "_MenuPartial";
                public readonly string _MenuShortcuts = "_MenuShortcuts";
                public readonly string _NavigationHeader = "_NavigationHeader";
                public readonly string _ResultNewScreenLayout = "_ResultNewScreenLayout";
                public readonly string _Search = "_Search";
                public readonly string Error = "Error";
            }
            public readonly string _AccessDenied = "~/Views/Shared/_AccessDenied.cshtml";
            public readonly string _ButtonPartial = "~/Views/Shared/_ButtonPartial.cshtml";
            public readonly string _ColumnFilter = "~/Views/Shared/_ColumnFilter.cshtml";
            public readonly string _ContainerSettings = "~/Views/Shared/_ContainerSettings.cshtml";
            public readonly string _GuestLayout = "~/Views/Shared/_GuestLayout.cshtml";
            public readonly string _LanguageSection = "~/Views/Shared/_LanguageSection.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginLayout = "~/Views/Shared/_LoginLayout.cshtml";
            public readonly string _MenuPartial = "~/Views/Shared/_MenuPartial.cshtml";
            public readonly string _MenuShortcuts = "~/Views/Shared/_MenuShortcuts.cshtml";
            public readonly string _NavigationHeader = "~/Views/Shared/_NavigationHeader.cshtml";
            public readonly string _ResultNewScreenLayout = "~/Views/Shared/_ResultNewScreenLayout.cshtml";
            public readonly string _Search = "~/Views/Shared/_Search.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string ComboBox = "ComboBox";
                public readonly string ComboBoxSearchable = "ComboBoxSearchable";
                public readonly string Currency = "Currency";
                public readonly string Date = "Date";
                public readonly string DateTime = "DateTime";
                public readonly string DateWitMonth = "DateWitMonth";
                public readonly string Decimal = "Decimal";
                public readonly string FileBrowser = "FileBrowser";
                public readonly string FileBrowserRemovable = "FileBrowserRemovable";
                public readonly string HBool = "HBool";
                public readonly string MultiSelectComboBox = "MultiSelectComboBox";
                public readonly string Number = "Number";
                public readonly string Password = "Password";
                public readonly string String = "String";
                public readonly string TextArea = "TextArea";
                public readonly string Time = "Time";
                public readonly string Upload = "Upload";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
